# permissions for end users to view poddistributors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: poddistributor-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: versprei
    app.kubernetes.io/part-of: versprei
    app.kubernetes.io/managed-by: kustomize
  name: poddistributor-viewer-role
rules:
- apiGroups:
  - versprei.versprei.io
  resources:
  - poddistributors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - versprei.versprei.io
  resources:
  - poddistributors/status
  verbs:
  - get
