---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - versprei.versprei.io
  resources:
  - poddistributors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - versprei.versprei.io
  resources:
  - poddistributors/finalizers
  verbs:
  - update
- apiGroups:
  - versprei.versprei.io
  resources:
  - poddistributors/status
  verbs:
  - get
  - patch
  - update
