---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spread-webhook-service-role
  namespace: default
rules:
- apiGroups:
  - 'versprei.versprei.io'
  - ''
  - 'apps'
  resources:
  - 'poddistributors'
  - 'pods'
  verbs:
  - 'get'
  - 'list'