---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spread-webhook-service-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spread-webhook-service-role
subjects:
  - kind: ServiceAccount
    name: spread-webhook-service-sa
    namespace: default